name: lws
main: com.govnoslav.SigmaWarsMain
load: POSTWORLD
version: 1.4
api-version: 1.21
description: Lucky Wars Baffled Eblan Chorn Pild ZV Goida plugin 52 666 sigma
authors: [GovnoSlav]
softdepend: []
commands:
  reload:
    usage: /reload
    permission: itemfix.reload
  rotatemap:
    description: "Повернуть куб 320×320×320 вокруг X"
    usage: "/rotatemap"
    permission: rotatemap.use
  regen:
    description: Управление регенерацией
    usage: /regen <add|set|multiple> <value> <selector> [duration, 0 for infinite]
    permission: sigmawars.regen
  motion:
    description: Управление вектором Motion у сущностей
    usage: /motion <set|add> <x> <y> <z> <цели>  или  /motion multiple <scalar> <цели>
    permission: sigmawars.motion
  clonetonexus:
    description: Clone region 11x11x11 to Nexus at random coords
    usage: /clonetonexus
  antigravity:
    description: antigravities blocks around
    usage: /antigravity
permissions:
  itemfix.reload:
    default: op
  rotatemap.use:
    description: "Позволяет использовать команду /rotatemap"
    default: op
  sigmawars.regen:
    default: op
  sigmawars.motion:
    default: op